// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlayer(arg1, arg2) {
  return window['go']['main']['App']['AddPlayer'](arg1, arg2);
}

export function CancelCurrentRound() {
  return window['go']['main']['App']['CancelCurrentRound']();
}

export function CheckAdminCredentials(arg1, arg2) {
  return window['go']['main']['App']['CheckAdminCredentials'](arg1, arg2);
}

export function ClearAllResultsInRound(arg1) {
  return window['go']['main']['App']['ClearAllResultsInRound'](arg1);
}

export function ClearMatchResult(arg1, arg2) {
  return window['go']['main']['App']['ClearMatchResult'](arg1, arg2);
}

export function ExportAllRoundsPairingsToPDF() {
  return window['go']['main']['App']['ExportAllRoundsPairingsToPDF']();
}

export function ExportRoundPairingsToPDF(arg1) {
  return window['go']['main']['App']['ExportRoundPairingsToPDF'](arg1);
}

export function ExportStandingsToPDF() {
  return window['go']['main']['App']['ExportStandingsToPDF']();
}

export function GetCurrentRound() {
  return window['go']['main']['App']['GetCurrentRound']();
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function GetStandings() {
  return window['go']['main']['App']['GetStandings']();
}

export function GetTournamentInfo() {
  return window['go']['main']['App']['GetTournamentInfo']();
}

export function GoBackToPreviousRound() {
  return window['go']['main']['App']['GoBackToPreviousRound']();
}

export function InitTournament(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitTournament'](arg1, arg2, arg3);
}

export function InitTournamentWithPlayerIDs(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitTournamentWithPlayerIDs'](arg1, arg2, arg3);
}

export function ListPlayers() {
  return window['go']['main']['App']['ListPlayers']();
}

export function NextRound() {
  return window['go']['main']['App']['NextRound']();
}

export function RecordResult(arg1, arg2) {
  return window['go']['main']['App']['RecordResult'](arg1, arg2);
}

export function SaveAllRoundsPairingsToPDF() {
  return window['go']['main']['App']['SaveAllRoundsPairingsToPDF']();
}

export function SaveRoundPairingsToPDF(arg1) {
  return window['go']['main']['App']['SaveRoundPairingsToPDF'](arg1);
}

export function SaveStandingsToPDF() {
  return window['go']['main']['App']['SaveStandingsToPDF']();
}
