// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CheckAdminCredentials(arg1:string,arg2:string):Promise<boolean>;

export function GetCurrentRound():Promise<model.Round>;

export function GetPlayers():Promise<Array<model.Player>>;

export function GetTournamentInfo():Promise<model.Tournament>;

export function InitTournament(arg1:string,arg2:Array<string>):Promise<boolean>;

export function InitTournamentWithPlayerIDs(arg1:string,arg2:Array<string>):Promise<boolean>;

export function ListPlayers():Promise<Array<model.Player>>;

export function NextRound():Promise<boolean>;

export function RecordResult(arg1:number,arg2:string):Promise<boolean>;
