// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddPlayer(arg1:string,arg2:string):Promise<string>;

export function CancelCurrentRound():Promise<boolean>;

export function CheckAdminCredentials(arg1:string,arg2:string):Promise<boolean>;

export function ClearAllResultsInRound(arg1:number):Promise<boolean>;

export function ClearMatchResult(arg1:number,arg2:number):Promise<boolean>;

export function ExportAllRoundsPairingsToPDF():Promise<Array<number>>;

export function ExportRoundPairingsToPDF(arg1:number):Promise<Array<number>>;

export function ExportStandingsToPDF():Promise<Array<number>>;

export function GetCurrentRound():Promise<model.Round>;

export function GetPlayers():Promise<Array<model.Player>>;

export function GetStandings():Promise<Array<model.Player>>;

export function GetTournamentInfo():Promise<model.Tournament>;

export function GoBackToPreviousRound():Promise<boolean>;

export function InitTournament(arg1:string,arg2:string,arg3:Array<string>):Promise<boolean>;

export function InitTournamentWithPlayerIDs(arg1:string,arg2:string,arg3:Array<string>):Promise<boolean>;

export function ListPlayers():Promise<Array<model.Player>>;

export function NextRound():Promise<boolean>;

export function RecordResult(arg1:number,arg2:string):Promise<boolean>;

export function SaveAllRoundsPairingsToPDF():Promise<string>;

export function SaveRoundPairingsToPDF(arg1:number):Promise<string>;

export function SaveStandingsToPDF():Promise<string>;
