// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdminCredentials(arg1, arg2) {
  return window['go']['main']['App']['CheckAdminCredentials'](arg1, arg2);
}

export function GetCurrentRound() {
  return window['go']['main']['App']['GetCurrentRound']();
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function GetTournamentInfo() {
  return window['go']['main']['App']['GetTournamentInfo']();
}

export function InitTournament(arg1, arg2) {
  return window['go']['main']['App']['InitTournament'](arg1, arg2);
}

export function InitTournamentWithPlayerIDs(arg1, arg2) {
  return window['go']['main']['App']['InitTournamentWithPlayerIDs'](arg1, arg2);
}

export function ListPlayers() {
  return window['go']['main']['App']['ListPlayers']();
}

export function NextRound() {
  return window['go']['main']['App']['NextRound']();
}

export function RecordResult(arg1, arg2) {
  return window['go']['main']['App']['RecordResult'](arg1, arg2);
}
